#%RAML 1.0 Library

types:
  matchingField:
    type: object
    properties:
      MatchingFieldName:
        type: string
        required: true
        example: "Id"
        minLength: 1
      MatchingFieldValue:
        type: string
        required: true
        example: "0039p00000XkzVLAAZ"
        minLength: 1