#%RAML 1.0 Library

types:
  userExists:
    properties:
      MatchingFieldName: 
        type: string
        required: true 
        example: "Email"
        minLength: 1
      MatchingFieldValue: 
        type: string
        required: true 
        example: "test@gmail.com"
        minLength: 1
