http.port=8081
mule.prcAPI=https://bcna-process-api-0vpirc.5sc6y6-3.usa-e2.cloudhub.io/api
mule.client_id=![KYk6Csibq4NsuEDzTHlbdZB/73/7v8CekNUJzmIAhcljeOtyCqqwqg==]
mule.client_secret=![WZ0zL1znRqwdIlqsLZ4WjY5UTUXxgTektyhRSDj4zGRCoxu1UjF6Qw==]
API_ID=19530066